name: CI

on: [push]

jobs:
  build:
    name: Build Next.js UI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: yarn
      - name: Build Next.js
        working-directory: src/ui
        run: ../../node_modules/.bin/next build
        env:
          CI: true
          NODE_ENV: production

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: yarn
      - name: Check prettier
        run: yarn prettier --list-different  '**/*.{ts,tsx}'

  typescript:
    name: Run TypeScript Compiler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: yarn
      - name: Top level tsc
        run: yarn tsc
        env:
          CI: true
      - name: UI tsc
        working-directory: src/ui
        run: ../../node_modules/.bin/tsc

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: yarn
      - name: Unit tests
        run: yarn test
