name: Check Prettier

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Check prettier
        run: yarn prettier --list-different  '**/*.{ts,tsx}'
