name: Run TypeScript Compiler

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Top level tsc
        run: yarn tsc
        env:
          CI: true
      - name: UI tsc
        working-directory: ui
        run: ../node_modules/.bin/tsc
